services:
  php-fpm:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: ./docker/php-fpm/Dockerfile  # Use the custom Dockerfile
    container_name: php-fpm
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.34
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
    ports:
      - "3334:3306"

  sysbench:
    image: perconalab/sysbench
    depends_on:
      - mysql
    volumes:
      - ./mysql-test.lua:/sysbench/scripts/mysql-test.lua

volumes:
  mysql_data: